#!/bin/bash 

# this script is created to install multiple applications at once in a server and it will store the logs of each step 

USERID=$(id -u)
USERNAME=$USER

LOGS_FOLDER="/var/log/shell_logs"
SCRIPT_NAME=$(basename $0)
LOG_FILE="$LOGS_FOLDER/$SCRIPT_NAME.log"

mkdir -p $LOGS_FOLDER
echo script executed date is :: $(date) | tee -a &>> $LOG_FILE

if [ $USERID -eq 0 ]

then 
    echo " $USERNAME has root privlages " | tee -a &>> $LOG_FILE
else  
    echo " error:: $USERNAME don't have root privlages " | tee -a &>> $LOG_FILE
    exit 1
fi 

VALIDATE() {
    if [ $@ -eq 0 ]
    then 
        echo " successfully installed $@ "
    else 
        echo " error:: failed to install $@ "
    fi
}

dnf list installed $@ &>> $LOG_FILE
 
  if [ $? -ne 0 ]
    then 
        echo " $@ is not installed, installing now..." | tee -a &>> $LOG_FILE
        
        dnf install $@ -y
        VALIDATE $? "$@"
    else
        echo "$@ is already isntalled in server nothing to do .." | tee -a &>> $LOG_FILE
        exit 1
    
  fi 


