#!/bin/bash

USERID=$(id -u)
R=\e[31m
G=\e32m
Y=\e[33m
N=\e[0m

LOG_FOLDER="/var/log/shell-scripts"
SCRIPT_NAME="$0"
LOG_FILE="$LOG_FOLDER/$SCRIPT_NAME.log"

mkdir -p /var/log/shell-scripts

if [ $USERID -eq 0 ]
   then 
        echo " you have root privlages"
    else
        echo "error :: you don't have root user privlages" 
    exit 1   

fi   

VALIDATE (){
    if [ $1 -eq 0 ]
    then 
        echo " $1 successfully installed in yuor server"
    else
        echo " $1 installation failed in your server"  
}

dnf list installed httpd &>> $LOG_FILE
if [ $? -ne 0 ]

then 
    echo "httpd installed in your server "

    dnf install httpd -y &>> $LOG_FILE
    $VALDIATE $? "httpd"
else 
    echo "httpd is already installed in your server nothing to do"
fi

dnf list installed nginx &>> $LOG_FILE
if [ $? -ne 0 ]

then 
    echo "nginx installed in your server "

    dnf install nginx -y &>> $LOG_FILE
    $VALDIATE $? "nginx"
else 
    echo "nginx is already installed in your server nothing to do"
fi

dnf list installed python3 &>> $LOG_FILE
if [ $? -ne 0 ]

then 
    echo "python3 installed in your server "

    dnf install python3 -y &>> $LOG_FILE
    $VALDIATE $? "python3"
else 
    echo "python3 is already installed in your server nothing to do" &>> $LOG_FILE
fi


